# dnsmasq conf for segment guest
# generated for iface=wlp2s0.200 (exists=True)
interface=wlp2s0.200
bind-interfaces
dhcp-range=192.168.2.100,192.168.2.200,12h
dhcp-option=option:router,192.168.2.1
dhcp-option=option:dns-server,192.168.2.1
